version: '3.7'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - .:/db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATA: ${POSTGRES_DATA}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

  back:
    build: ./back
    container_name: alef-back
    volumes:
      - ./back:/app
    ports:
      - ${PORT}:${PORT}
    environment:      
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm i -g @nestjs/cli; npm install; npm run start:dev"

  adminer:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8090:80

volumes:
  postgres_db:



